# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install
# RUN NODE_ENV=development npm i


# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Install a lightweight web server to serve the static files
RUN npm install -g serve

# Expose the port that the app will run on
EXPOSE 3000

# Command to run the web server and serve the React app
CMD ["serve", "-s", "dist", "-l", "3000"]
