
name: Deploy dashni to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  BPD:
    runs-on: ubuntu-24.04
  
    env:
      DOCKER_IMAGE: "dashni-${{ github.ref_name }}:${{ github.sha }}"
      DOCKER_IMAGE_TAR: "dashni-${{ github.ref_name }}.tar"

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

        
    - name: Load Docker Image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker load -i frontend-${{ env.DOCKER_IMAGE_TAR }}/frontend-${{ env.DOCKER_IMAGE_TAR }}
          docker load -i backend-${{ env.DOCKER_IMAGE_TAR }}/backend-${{ env.DOCKER_IMAGE_TAR }}
    
    - name: Update Docker Compose 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          yq w -i dashni/docker-compose.yml 'services.frontend.image' 'frontend-${{ github.ref_name }}:${{ github.sha }}'
          yq w -i dashni/docker-compose.yml 'services.backend.image' 'backend-${{ github.ref_name }}:${{ github.sha }}'
    
    - name: Recreate images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          cd dashni
          docker rollout frontend-${{ github.ref_name }}:${{ github.sha }}
          docker rollout backend-${{ github.ref_name }}:${{ github.sha }}
        


          

