
name: Deploy dashni to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  BPD:
    runs-on: ubuntu-24.04
  
    env:
      DOCKER_IMAGE: "dashni-${{ github.ref_name }}:${{ github.sha }}"
      DOCKER_IMAGE_TAR: "dashni-${{ github.ref_name }}.tar"

    steps:

        
    - name: Load Docker image(frontend)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker load -i frontend-${{ env.DOCKER_IMAGE_TAR }}/frontend-${{ env.DOCKER_IMAGE_TAR }}
          docker load -i backend-${{ env.DOCKER_IMAGE_TAR }}/backend-${{ env.DOCKER_IMAGE_TAR }}
          

