name: Create dashni atrifactory

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses:  actions/checkout@v4

    - name: print content
      run: ls

    - name: Build Docker image
      run: echo "wauuu image has been builded"


    - name: Push image to private docker
      run: echo ${{ secrets.HOST }}

    - name: executing remote
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: host.dosh.ge
        username: ${{ secrets.FINGERPRINT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
      
