
name: Deploy dashni to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  BPD:
    runs-on: ubuntu-24.04
  
    env:
      DOCKER_IMAGE: "dashni-${{ github.ref_name }}:${{ github.sha }}"
      DOCKER_IMAGE_TAR: "dashni-${{ github.ref_name }}.tar"

    steps:
    - name: Checkout repository
      uses:  actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend
      run: |
        cd backend
        docker build . -t backend-${{ env.DOCKER_IMAGE }} --platform linux/amd64

    - name: Build fronted
      run: |
        cd fronted
        docker build . -t fronted-${{ env.DOCKER_IMAGE }} --platform linux/amd64

    - name: Save Docker Image backend
      run: |
        docker save --output backend-${{ env.DOCKER_IMAGE_TAR }} backend-${{ env.DOCKER_IMAGE }} 
        chmod 664 backend-${{ env.DOCKER_IMAGE_TAR }}

    - name: Save Docker Image fronted
      run: |
        docker save --output fronted-${{ env.DOCKER_IMAGE_TAR }} fronted-${{ env.DOCKER_IMAGE }} 
        chmod 664 fronted-${{ env.DOCKER_IMAGE_TAR }}

    - name: Copy Docker image(backend) to host
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
        source: "backend-${{ env.DOCKER_IMAGE_TAR }}"
        target: "backend-${{ env.DOCKER_IMAGE_TAR }}"

    - name: Copy Docker image(fronted) to host
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
        source: "fronted-${{ env.DOCKER_IMAGE_TAR }}"
        target: "fronted-${{ env.DOCKER_IMAGE_TAR }}"

